"use client";
import {useEffect,useRef,useState} from 'react';
import {ShieldCheck,ArrowUpRight,Play,GitBranch,Mail,Zap,Download,RotateCcw,Square,ArrowRight,Check,Search,ExternalLink,Activity} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {summarize} from '@/lib/pipeline.mjs';
import emails from '@/data/emails.json';
type Row=typeof emails[number]&{jev?:any;kimi?:any;final?:string;escalated?:boolean;error?:string;status?:string;stage?:string;failedCalls?:any[]};
type Recording={rows:Row[];events:any[];threshold:number;durationMs?:number;startedAt?:string};
const money=(n:number)=>'$'+n.toFixed(n<.01?5:4);
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
export default function Page(){
 const [rows,setRows]=useState<Row[]>(emails.map(email=>({...email,stage:"queued"}))),[recording,setRecording]=useState<Recording|null>(null),[threshold,setThreshold]=useState(95),[mode,setMode]=useState<'live'|'replay'|null>(null),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Row|null>(null),[notice,setNotice]=useState(''),[elapsed,setElapsed]=useState(0),[loaded,setLoaded]=useState(false);
 const cancel=useRef<AbortController|null>(null),timers=useRef<ReturnType<typeof setTimeout>[]>([]),start=useRef(0),latest=useRef<Row[]>([]),activeThreshold=useRef(95);
 useEffect(()=>{fetch('/api/recording').then(r=>r.json() as Promise<Recording>).then((d:Recording)=>{setRecording(d);if(d.rows?.length){setRows(d.rows);latest.current=d.rows;setThreshold(d.threshold*100);activeThreshold.current=d.threshold*100;setMode('replay');setElapsed(d.durationMs??0)}setLoaded(true)}).catch(()=>{setLoaded(true);setNotice('Recorded run could not be loaded.')});return()=>{cancel.current?.abort();timers.current.forEach(clearTimeout)}},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'get_fraud_run_summary',title:'Read fraud run summary',description:'Read the visible run summary without starting paid inference or changing state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object');return {threshold:activeThreshold.current/100,...summarize(latest.current)}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 useEffect(()=>{if(!busy)return;const timer=setInterval(()=>setElapsed(Date.now()-start.current),100);return()=>clearInterval(timer)},[busy]);
 function apply(event:any){if(event.type==='stage'){setRows(prev=>{const old=prev.find(r=>r.id===event.id);const next=old?prev.map(r=>r.id===event.id?{...r,stage:event.stage}:r):[...prev,{...emails.find(e=>e.id===event.id)!,stage:event.stage}];latest.current=next;return next})}else if(event.row){setRows(prev=>{const next=[...prev.filter(r=>r.id!==event.row.id),{...event.row,stage:event.type==='result'?'done':event.row.escalated?'kimi':'done'}];latest.current=next;return next})}}
 function stop(){cancel.current?.abort();timers.current.forEach(clearTimeout);timers.current=[];setBusy(false);setNotice(mode==='live'?'Stopped. Requests already sent may still be billed; partial results remain visible.':'Replay paused. Start again to replay from the beginning.')}
 function reset(){setRows(emails.map(email=>({...email,stage:'queued'})));latest.current=emails;setElapsed(0);setNotice('');setSelected(null);setMode(null)}
 function replay(){if(!recording?.rows.length)return;reset();setMode('replay');setBusy(true);setThreshold(recording.threshold*100);activeThreshold.current=recording.threshold*100;start.current=Date.now();const events=recording.events?.length?recording.events:recording.rows.map((row,i)=>({type:'result',row,at:i*100}));const end=Math.max(...events.map(e=>e.at),1);for(const event of events)timers.current.push(setTimeout(()=>apply(event),event.at/end*9500));timers.current.push(setTimeout(()=>{setRows(recording.rows);latest.current=recording.rows;setBusy(false);setElapsed(10000)},10000));}
 async function live(){reset();activeThreshold.current=threshold;setMode('live');setBusy(true);start.current=Date.now();const abort=new AbortController();cancel.current=abort;try{const response=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({threshold:threshold/100}),signal:abort.signal});if(!response.ok){const d=await response.json() as {error?:string};throw Error(d.error??'Unable to start run')}const reader=response.body!.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()??'';for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.type==='done'){setRows(event.rows);latest.current=event.rows;if(event.rows.length<100)setNotice('Run ended early after a provider error. Inspect the error and try again.')}else apply(event)}}}catch(e:any){if(e.name!=='AbortError')setNotice(e.message)}finally{setBusy(false)}}
 function download(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),mode,threshold:activeThreshold.current/100,summary:summarize(rows),rows,source:'https://huggingface.co/datasets/difraud/difraud'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='relay-fraud-results.json';a.click();URL.revokeObjectURL(url)}
 const summary=summarize(rows),classified=summary.completed,finished=classified===100,accuracy=classified?summary.correct/classified:0;
 const visible=[...rows].reverse().filter(r=>(filter==='all'||filter==='escalated'&&r.escalated||filter==='fraud'&&r.final==='fraud'||filter==='errors'&&(r.error||r.final&&r.final!==r.label))&&(!query||`${r.id} ${r.text}`.toLowerCase().includes(query.toLowerCase())));
 const selectedRow=selected?rows.find(r=>r.id===selected.id)??selected:null;
 const current=rows.filter(r=>r.stage==='kimi'||r.stage==='jev').at(-1);
 return <main>
 <header><a className="brand" href="/"><ShieldCheck size={25}/> relay<span> / fraud intelligence</span></a><div className="header-right"><span className="top-label">JEV × KIMI K3</span><a href="https://huggingface.co/datasets/difraud/difraud" target="_blank" rel="noreferrer">Dataset <ExternalLink size={13}/></a></div></header>
 <section className="heading"><div><div className="eyebrow">SMALL MODEL. BIG BACKUP.</div><h1>A second opinion.<br/><span>Only when it matters.</span></h1><p>Jev handles the clear cases. Kimi K3 takes a closer look.</p></div><div className="run-controls"><div className="buttons">{busy?<button className="secondary" onClick={stop}><Square size={14}/> Stop {mode==='replay'?'replay':'run'}</button>:<><button className="secondary" disabled={!recording?.rows.length} onClick={replay}><Play size={15}/> 10s replay</button><button className="primary" onClick={live}><Zap size={16}/> Run live <ArrowUpRight size={16}/></button></>}</div><span className="run-caption">{busy?mode==='replay'?'Recorded API results · accelerated playback':'Live inference · 5 emails in parallel':recording?.rows.length?'Replay real results, or make fresh API calls':'100 labeled emails · ready to classify'}</span></div></section>
 {notice&&<div className="notice" role="alert">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message">×</button></div>}
 <section className={`pipeline ${busy?'running':''}`}><div className="pipeline-head"><span><i className={busy?'status-dot active':'status-dot'}/>{busy?mode==='replay'?'REPLAYING RECORDED DECISIONS':'LIVE INFERENCE':finished?'RUN COMPLETE':'THE CONFIDENCE ROUTER'}</span><div className="threshold-control"><label htmlFor="confidence-slider">Acceptance threshold <b>{threshold}%</b></label><Slider id="confidence-slider" aria-label="Confidence threshold" min={50} max={100} step={1} value={[threshold]} disabled={busy} onValueChange={([v])=>setThreshold(v)}/></div></div>
 <div className="flow"><div className="node"><div className="node-icon"><Mail size={22}/></div><b>100 emails</b><small>DIFrauD · 50 fraud / 50 safe</small></div><div className="wire"><i/></div><div className={`node jev ${current?.stage==='jev'?'working':''}`}><div className="node-icon"><Zap size={23}/></div><b>Jev <span className="node-tag">FAST PATH</span></b><small>{summary.jevCount?`${summary.jevCount} classified · ${summary.jevMedianMs} ms median`:'Structured classification + confidence'}</small></div><div className="wire"><i/></div><div className="gate"><div className="gate-icon"><GitBranch size={23}/></div><span>≥ {busy||summary.jevCount?activeThreshold.current:threshold}% <b>accept</b></span><small>below threshold ↓</small></div><div className="wire purple"><i/></div><div className={`node kimi ${current?.stage==='kimi'?'working':''}`}><div className="node-icon"><Activity size={23}/></div><b>Kimi K3 <span className="node-tag">REVIEW</span></b><small>{summary.escalated?`${summary.reviewed} reviewed / ${summary.escalated} escalated`:'Independent second opinion'}</small></div></div>
 <div className="pipeline-bottom"><span>{busy?current?`${current.id} · ${current.stage==='kimi'?'Taking a closer look with Kimi K3':'Classifying with Jev'}…`:'Starting pipeline…':finished?`${summary.accepted} fast-path decisions · ${summary.escalated} sent for review`:'Confident decisions stay fast. Uncertain decisions get more attention.'}</span><span>{mode==='replay'?'RECORDED RUN':mode==='live'?'LIVE RUN':'READY'}{elapsed>0?` / ${(elapsed/1000).toFixed(1)}s`:''}</span></div><Progress aria-label="Emails classified" value={classified} className="run-progress"/></section>
 <section className="stats"><div className="stat"><span>Emails classified</span><strong>{classified}<em> / 100</em></strong><small>{classified?`${summary.fraud} flagged as fraud`:'Awaiting classification'}</small></div><div className="stat"><span>Escalated to Kimi K3</span><strong className="purple-text">{summary.escalated}<em> / {summary.jevCount||100}</em></strong><small>{summary.jevCount?`${Math.round(summary.accepted/summary.jevCount*100)}% resolved by Jev alone`:'Only uncertain cases escalate'}</small></div><div className="stat"><span>Label accuracy</span><strong>{classified?pct(accuracy):'—'}<span className="mini-icon"><ShieldCheck size={19}/></span></strong><small>{classified?`${summary.correct} correct of ${classified} completed`:'Compared with dataset labels'}</small></div><div className="stat cost-stat"><span>Total inference cost</span><strong>{rows.length?money(summary.cost):'$0.0000'}</strong><small>{!summary.jevCount?'No API calls in this view':summary.unknownCosts?'Partial total · some costs unavailable':summary.estimatedCosts?'Includes token-based estimates':'Provider-reported usage'}{mode==='replay'?' · original run':''}</small></div></section>
 <div className="results-grid"><section className="panel decision-panel"><div className="panel-title"><h2>Decision stream <span className="count-badge">{rows.length}</span></h2><div className="panel-actions"><button title="Reset view" aria-label="Reset view" disabled={busy} onClick={reset}><RotateCcw size={15}/></button><button title="Export results" aria-label="Export results" disabled={!rows.length||busy} onClick={download}><Download size={16}/></button></div></div><div className="table-tools"><Tabs value={filter} onValueChange={setFilter}><TabsList className="filter-tabs"><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="escalated">Escalated</TabsTrigger><TabsTrigger value="fraud">Fraud</TabsTrigger><TabsTrigger value="errors">Errors</TabsTrigger></TabsList></Tabs><label className="search"><Search size={14}/><input aria-label="Search emails" placeholder="Search emails" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="table-scroll"><Table><TableHeader><TableRow><TableHead>Email</TableHead><TableHead>Jev confidence</TableHead><TableHead>Route</TableHead><TableHead>Decision</TableHead></TableRow></TableHeader><TableBody>{visible.map(row=><TableRow key={row.id} className={row.stage==='kimi'?'reviewing':''}><TableCell><button className="email-open" onClick={()=>setSelected(row)}><span>{row.id}<ArrowUpRight size={12}/></span><p>{row.text.slice(0,95)}</p></button></TableCell><TableCell>{row.jev?<div className="confidence"><span>{pct(row.jev.confidence)}</span><div><i style={{width:`${row.jev.confidence*100}%`,background:row.escalated?'#bda0f5':'#b6de70'}}/></div></div>:<span className="muted">{row.stage==='queued'?'—':'Classifying…'}</span>}</TableCell><TableCell>{row.escalated?<span className="route purple-text"><GitBranch size={13}/> Kimi K3</span>:row.jev?<span className="route"><Zap size={13}/> Jev</span>:<span className="muted">—</span>}</TableCell><TableCell>{row.final?<span className={`decision ${row.final==='fraud'?'fraud':'legitimate'}`}>{row.final==='fraud'?'Fraud':'Legitimate'}</span>:row.error?<span className="decision fraud">Failed</span>:<span className="review-label">{row.stage==='kimi'?'Reviewing…':row.stage==='queued'?'Queued':'Analyzing…'}</span>}{row.final&&<span className={`label-check ${row.final===row.label?'match':'mismatch'}`} title={row.final===row.label?'Matches dataset label':'Disagrees with dataset label'}>{row.final===row.label?<Check size={12}/>: '×'}</span>}</TableCell></TableRow>)}</TableBody></Table>{!visible.length&&<div className="empty"><ShieldCheck/><h3>{rows.length?'No matching emails.':loaded?'Your pipeline is ready.':'Loading recorded results…'}</h3><p>{rows.length?'Try another filter or search.':'Run live to watch Jev classify and Kimi review.'}</p></div>}</div></section>
 <aside className="panel impact"><div className="panel-title"><h2>The cascade effect</h2><GitBranch size={16}/></div><div className="impact-body"><div className="impact-number">{summary.jevCount?Math.round(summary.accepted/summary.jevCount*100):0}<span>%</span></div><p>resolved by the small model</p><div className="split-bar"><div style={{width:`${summary.jevCount?summary.accepted/summary.jevCount*100:0}%`}}/></div><div className="legend"><span><i/>Jev only <b>{summary.accepted}</b></span><span><i/>Kimi review <b>{summary.escalated}</b></span></div><hr/><div className="cost-line"><span>Jev inference</span><b>{money(summary.jevCost)}</b></div><div className="cost-line"><span>Kimi K3 review</span><b>{money(summary.kimiCost)}</b></div><div className="cost-line"><span>Decisions changed</span><b>{summary.changed}</b></div><div className="cost-line"><span>Errors fixed / introduced</span><b>{summary.fixed} / {summary.regressed}</b></div><div className="cost-line"><span>Fraud recall</span><b>{summary.recall===null?'—':pct(summary.recall)}</b></div><div className="impact-note"><ShieldCheck size={17}/><span>{summary.jevCount?`Jev alone: ${pct(summary.jevCorrect/summary.jevCount)} label accuracy. ${classified?`Cascade: ${pct(accuracy)}.`:''}`:'Accuracy is measured against labels, separately from model confidence.'}</span></div></div></aside></div>
 <footer><span>RELAY / CONFIDENCE-GATED INFERENCE</span><span>100-email balanced demo · confidence ≠ accuracy · <a href="https://huggingface.co/datasets/difraud/difraud" target="_blank" rel="noreferrer">DIFrauD ↗</a></span></footer>
 <Sheet open={!!selectedRow} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{selectedRow?.id} · Decision detail</SheetTitle><SheetDescription>Original email, routing evidence, and independent review.</SheetDescription></SheetHeader>{selectedRow&&<div className="detail-body"><div className="detail-label">EMAIL CONTENT · UNTRUSTED TEXT</div><p className="email-text">{selectedRow.text}</p><div className="detail-label">JEV DECISION</div><p>{selectedRow.jev?.choice??'Pending'} · {selectedRow.jev?pct(selectedRow.jev.confidence):'—'} {selectedRow.jev?.confidenceBasis??'confidence'}</p><p className="muted">{!selectedRow.jev?'Awaiting classification':selectedRow.escalated?`Below ${activeThreshold.current}% → escalated to Kimi K3`:`At or above ${activeThreshold.current}% → accepted directly`}</p>{selectedRow.kimi&&<><div className="detail-label">KIMI K3 · INDEPENDENT REVIEW</div><p>{selectedRow.kimi.choice}</p><p className="review-reason">{selectedRow.kimi.reason}</p></>}<div className="detail-label">EVALUATION</div><p>Dataset label: <b>{selectedRow.label}</b> · Final: <b>{selectedRow.final??'Unresolved'}</b></p><p className="muted">Source test row {selectedRow.sourceRow}. Labels are never included in model requests.</p>{selectedRow.error&&<p className="notice">{selectedRow.error}</p>}<div className="detail-label">USAGE</div><p>Jev: {selectedRow.jev?.ms??'—'} ms · {selectedRow.jev?.inputTokens??'—'} input tokens{selectedRow.kimi?` | Kimi: ${(selectedRow.kimi.ms/1000).toFixed(1)}s · ${selectedRow.kimi.outputTokens} output tokens`:''}</p></div>}</SheetContent></Sheet>
 </main>
}
